// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xaaqqrcmaqppzrnzkfwg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhhYXFxcmNtYXFwcHpybnprZndnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4NzgxMDUsImV4cCI6MjA2NDQ1NDEwNX0.2fzt97MnicrZp0wPdiNR1iuzB7G45aLlqgiE7VqzD6c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);